mkdir SimpleBrowser-0.9.8
copy /Y README.txt SimpleBrowser-0.9.8
copy /Y READMEJP.txt SimpleBrowser-0.9.8
copy /Y LICENSE.txt SimpleBrowser-0.9.8
copy /Y SimpleBrowser.exe SimpleBrowser-0.9.8
copy /Y CancelPrinting.bat SimpleBrowser-0.9.8
copy /Y Downside_en.txt SimpleBrowser-0.9.8
copy /Y Downside_ja.txt SimpleBrowser-0.9.8
copy /Y LeftSide_en.txt SimpleBrowser-0.9.8
copy /Y LeftSide_ja.txt SimpleBrowser-0.9.8
copy /Y MenuAnchor_en.txt SimpleBrowser-0.9.8
copy /Y MenuAnchor_ja.txt SimpleBrowser-0.9.8
copy /Y MenuDefault_en.txt SimpleBrowser-0.9.8
copy /Y MenuDefault_ja.txt SimpleBrowser-0.9.8
copy /Y MenuImage_en.txt SimpleBrowser-0.9.8
copy /Y MenuImage_ja.txt SimpleBrowser-0.9.8
copy /Y MenuText_en.txt SimpleBrowser-0.9.8
copy /Y MenuText_ja.txt SimpleBrowser-0.9.8
copy /Y RightSide_en.txt SimpleBrowser-0.9.8
copy /Y RightSide_ja.txt SimpleBrowser-0.9.8
copy /Y Upside_en.txt SimpleBrowser-0.9.8
copy /Y Upside_ja.txt SimpleBrowser-0.9.8
copy /Y mshtmcid.h SimpleBrowser-0.9.8
copy /Y v2xker32.dll SimpleBrowser-0.9.8
copy /Y v2xol.dll SimpleBrowser-0.9.8
