//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// SimpleBrowser_res.rc

#define IDC_STATIC                          -1

#define IDB_SECURE                          100
#define IDB_INSECURE                        101

#define IDD_ABOUTBOX                        100
#define IDD_SETTINGS                        101
#define IDD_ADDLINK                         102
#define IDD_URLLIST                         103
#define IDD_FORBIDDEN                       104
#define IDD_DOWNLOADING                     105

#define IDR_DOTSMENU                        100

#define IDS_READY                           100
#define IDS_STOP                            101
#define IDS_REFRESH                         102
#define IDS_BACK                            103
#define IDS_NEXT                            104
#define IDS_GO                              105
#define IDS_LOADING                         106
#define IDS_HOMEPAGE                        107
#define IDS_EXECUTING_CMD                   108
#define IDS_HOME                            109
#define IDS_HTMLFILTER                      110
#define IDS_HITBLACKLIST                    111
#define IDS_TXTFILTER                       112
#define IDS_IMGFILTER                       113
#define IDS_PDFFILTER                       114
#define IDS_ALLFILTER                       115
#define IDS_SOURCE                          116
#define IDS_REGISTER_WND_FAIL               117
#define IDS_CREATE_WND_FAIL                 118
#define IDS_ACCESS_FAIL                     119
#define IDS_DOTS                            120
#define IDS_TITLE_TEXT                      121
#define IDS_NONAME                          122
#define IDS_ADD_LINK                        123
#define IDS_ENTER_TEXT                      124
#define IDS_UPSIDE                          125
#define IDS_DOWNSIDE                        126
#define IDS_LEFTSIDE                        127
#define IDS_RIGHTSIDE                       128
#define IDS_DEFAULTMENU                     129
#define IDS_IMAGEMENU                       130
#define IDS_TEXTMENU                        131
#define IDS_ANCHORMENU                      132
#define IDS_VIRUS_FOUND                     133
#define IDS_CLOSE                           134
#define IDS_DL_COMPLETE                     135
#define IDS_EXEFILTER                       136
#define IDS_DLLFILTER                       137
#define IDS_NO_VIRUS                        138
#define IDS_CANT_SCAN_VIRUS                 139
#define IDS_VIRUS_FOUND_DELETED             140
#define IDS_FAILED_TO_DL                    141
#define IDS_WAIT_SCAN_PLEASE                142
#define IDS_DL_QUIT_QUESTION                143
#define IDS_QUERY_URL                       144
#define IDS_DOWNLOAD_PROGRESS_0             145
#define IDS_DOWNLOAD_PROGRESS_1             146
#define IDS_DOWNLOAD_PROGRESS_2             147
#define IDS_DOWNLOAD_PROGRESS_3             148
#define IDS_SCAN_SKIPPED                    149
#define IDS_SECURITY_WARNING                150

#define ID_BACK                             20001
#define ID_NEXT                             20002
#define ID_STOP_REFRESH                     20003
#define ID_HOME                             20004
#define ID_ADDRESS_BAR                      20005
#define ID_GO                               20006
#define ID_BROWSER                          20007
#define ID_REFRESH                          20008
#define ID_STOP                             20009
#define ID_GO_TO_ADDRESS_BAR                20010
#define ID_PRINT                            20011
#define ID_PRINT_BANG                       20012
#define ID_PRINT_PREVIEW                    20013
#define ID_PAGE_SETUP                       20014
#define ID_SAVE                             20015
#define ID_VIEW_SOURCE_DONE                 20016
#define ID_DOTS                             20017
#define ID_VIEW_SOURCE                      20018
#define ID_ABOUT                            20019
#define ID_CREATE_SHORTCUT                  20020
#define ID_SETTINGS                         20021
#define ID_ADD_TO_COMBOBOX                  20022
#define ID_DOCUMENT_COMPLETE                20023
#define ID_EXIT                             20024
#define ID_NEW                              20025
#define ID_KIOSK                            20026
#define ID_KIOSK_OFF                        20027
#define ID_KIOSK_ON                         20028
#define ID_GO_URL                           20029
#define ID_EXECUTE_CMD                      20030
#define ID_CANCEL_PRINTING                  20031
#define ID_UP                               20032
#define ID_DOWN                             20033
#define ID_ZOOM_UP                          20034
#define ID_ZOOM_DOWN                        20035
#define ID_ZOOM_100                         20036
#define ID_SAVE_IMAGE_AS                    20037
#define ID_SAVE_TARGET_AS                   20038
#define ID_CUSTOM_LINK_01                   20039
#define ID_CUSTOM_LINK_02                   20040
#define ID_CUSTOM_LINK_03                   20041
#define ID_CUSTOM_LINK_04                   20042
#define ID_CUSTOM_LINK_05                   20043
#define ID_CUSTOM_LINK_06                   20044
#define ID_CUSTOM_LINK_07                   20045
#define ID_CUSTOM_LINK_08                   20046
#define ID_CUSTOM_LINK_09                   20047
#define ID_CUSTOM_LINK_10                   20048
#define ID_CUSTOM_LINK_11                   20049
#define ID_CUSTOM_LINK_12                   20050
#define ID_CUSTOM_LINK_13                   20051
#define ID_CUSTOM_LINK_14                   20052
#define ID_CUSTOM_LINK_15                   20053
#define ID_CUSTOM_LINK_16                   20054
#define ID_PARSE_CMDLINE                    20055

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    101
        #define _APS_NEXT_COMMAND_VALUE     20056
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
