//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// SimpleBrowser_res.rc

#define IDC_STATIC                          -1

#define IDB_SECURE                          100
#define IDB_INSECURE                        101

#define IDS_READY                           100
#define IDS_STOP                            101
#define IDS_REFRESH                         102
#define IDS_BACK                            103
#define IDS_NEXT                            104
#define IDS_GO                              105
#define IDS_LOADING                         106
#define IDS_HOMEPAGE                        107
#define IDS_EXECUTING_CMD                   108
#define IDS_HOME                            109
#define IDS_HTMLFILTER                      110
#define IDS_HITBLACKLIST                    111
#define IDS_TXTFILTER                       112
#define IDS_IMGFILTER                       113
#define IDS_PDFFILTER                       114
#define IDS_ALLFILTER                       115
#define IDS_SOURCE                          116
#define IDS_REGISTER_WND_FAIL               117
#define IDS_CREATE_WND_FAIL                 118

#define ID_BACK                             101
#define ID_NEXT                             102
#define ID_STOP_REFRESH                     103
#define ID_HOME                             104
#define ID_ADDRESS_BAR                      105
#define ID_GO                               106
#define ID_BROWSER                          107
#define ID_REFRESH                          108
#define ID_STOP                             109
#define ID_GO_TO_ADDRESS_BAR                110
#define ID_PRINT                            111
#define ID_PRINT_BANG                       112
#define ID_PRINT_PREVIEW                    113
#define ID_PAGE_SETUP                       114
#define ID_SAVE                             115
#define ID_VIEW_SOURCE_DONE                 116

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     117
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
